apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mutant-redis
spec:
  selector:
    matchLabels:
      app: mutant-redis
  serviceName: "mutant-redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: mutant-redis # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mutant-redis
          image: redis:latest
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: pvc-redis
              mountPath: /data
      volumes:
        - name: pvc-redis
          persistentVolumeClaim:
            claimName: pvc-redis
---
apiVersion: v1
kind: Service
metadata:
  name: mutant-redis
  labels:
    app: mutant-redis
spec:
  ports:
    - port: 6379
      name: mutant-redis
      targetPort: mutant-redis
  clusterIP: None
  selector:
    app: mutant-redis