apiVersion: v1
kind: Service
metadata:
  name: mutant-redis
  labels:
    app: mutant-redis
spec:
  ports:
    - port: 6379
      name: mutant-redis
      targetPort: mutant-redis
  clusterIP: None
  selector:
    app: mutant-redis